#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : codecov
Version  : 2.0.17
Release  : 9
URL      : https://files.pythonhosted.org/packages/23/6f/73f78e6346741b618068def5d79da3b990ce72330f565a9f6e642e2ff1cf/codecov-2.0.17.tar.gz
Source0  : https://files.pythonhosted.org/packages/23/6f/73f78e6346741b618068def5d79da3b990ce72330f565a9f6e642e2ff1cf/codecov-2.0.17.tar.gz
Summary  : Hosted coverage reports for GitHub, Bitbucket and Gitlab
Group    : Development/Tools
License  : Apache-2.0
Requires: codecov-bin = %{version}-%{release}
Requires: codecov-python = %{version}-%{release}
Requires: codecov-python3 = %{version}-%{release}
Requires: coverage
Requires: requests
BuildRequires : buildreq-distutils3
BuildRequires : coverage
BuildRequires : requests

%description
Codecov Global Python Uploader [![codecov.io](https://codecov.io/github/codecov/codecov-python/coverage.svg?branch=master)](https://codecov.io/github/codecov/codecov-python)
=======
| [https://codecov.io/][1] | [@codecov][2] | [hello@codecov.io][3] |
| ------------------------ | ------------- | --------------------- |

%package bin
Summary: bin components for the codecov package.
Group: Binaries

%description bin
bin components for the codecov package.


%package python
Summary: python components for the codecov package.
Group: Default
Requires: codecov-python3 = %{version}-%{release}

%description python
python components for the codecov package.


%package python3
Summary: python3 components for the codecov package.
Group: Default
Requires: python3-core
Provides: pypi(codecov)
Requires: pypi(coverage)
Requires: pypi(requests)

%description python3
python3 components for the codecov package.


%prep
%setup -q -n codecov-2.0.17
cd %{_builddir}/codecov-2.0.17

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1584472403
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/codecov

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
